-- Cria o Banco de Dados GESTAOPSICOLOGIA
CREATE DATABASE GESTAOPSICOLOGIA;

-- Cria a Tabela PACIENTES
CREATE TABLE PACIENTES(
ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_PACIENTE VARCHAR(80) NOT NULL,
DATA_CRIACAO_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
D_E_L_E_T_ VARCHAR(1) NOT NULL
);

INSERT INTO pacientes(NOME_PACIENTE, D_E_L_E_T_) VALUES('Fernanda Moraes', '');

SELECT * FROM pacientes;

-- Cria a Tabela AGENDAMENTOS
CREATE TABLE AGENDAMENTOS(
ID_AGENDAMENTO INT AUTO_INCREMENT PRIMARY KEY,
ID_PACIENTE INT NOT NULL,
DATA_HORA DATETIME NOT NULL,
VALOR DECIMAL(10,2) NOT NULL,
STATUS_PAGAMENTO VARCHAR(20) NOT NULL,
DATA_CRIACAO_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
D_E_L_E_T_ VARCHAR(1) NOT NULL,
CONSTRAINT FK_AGENDAMENTOS_PACIENTES FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

INSERT INTO AGENDAMENTOS(ID_PACIENTE, DATA_HORA, VALOR, STATUS_PAGAMENTO, D_E_L_E_T_) VALUES(1, '2024-02-13 10:00:00', 200, 'Pendente', '');

SELECT * FROM agendamentos;